name: CI/CD Workflow

on:
  push:
    branches: ["main"]
    paths:
      - src/**
      - Cargo.*
      - Dockerfile
      - .dockerignore
      - ./.github/workflows/*.yml
  workflow_dispatch:

jobs:
  rust_ci:
    uses: ./.github/workflows/rust.yml

  container_cd:
    uses: ./.github/workflows/container.yml
    needs: rust_ci