name: Create resume release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/raian621/resume-builder

    steps:
      - uses: actions/checkout@v4

      - name: compile resume using pdflatex
        run: pdflatex resume.tex

      - name: create release for resume
        uses: softprops/action-gh-release@v1
        with:
          files: resume.pdf
          tag_name: "${{ github.ref }}"