name: Create resume release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/raian621/resume-builder

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: compile resume using pdflatex
        run: pdflatex resume.tex

      - name: create release for resume
        uses: softprops/action-gh-release@v1
        with:
          files: resume.pdf
          # use branch name (e.g. fullstack, devops, etc.) 
          tag_name: "${{ steps.extract_branch.outputs.branch }}"